# .github/workflows/deploy-ghp.yml

# Workflow name
name: Build and Publish storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - "docs-deploy"

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    ## Errors ( branch protection rules) (https://github.com/jonniebigodes/test-deployer-gh-actions/actions/runs/6630307419)
    #environment:
    # name: github-pages
    # url: ${{ steps.build-publish.outputs.page_url }}
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      #- name: Install dependencies
      #  run: yarn
      #- name: Build Storybook
      #  run: yarn build-storybook --quiet
      #👇 Adds Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
        with:
          install_command: yarn install
          build_command: yarn build-storybook
          path: storybook-static
          checkout: false
