# .github/workflows/deploy-ghp.yml

# Workflow name
name: Build and Publish storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - "docs-deploy"

# List of jobs
jobs:
  deploy:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn
      #- name: Build Storybook
      #  run: yarn build-storybook --quiet
      #👇 Adds Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: storybook-static
